
apiVersion: batch/v1
kind: Job
metadata:
  name: restarter
  namespace: xmrig
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/jithinkv20/kuberest:master
        name: restarter
        env:
        - name: KUBECONFIG
          value: "/config/config"
        volumeMounts:
        - mountPath: /config
          name: config
        resources: {}
      restartPolicy: Never
      volumes:
      - name: config
        hostPath:
          # directory location on host
          path: /root
          # this field is optional
          type: Directory
status: {}
