apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: restarter
  name: restarter
  namespace: xmrig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restarter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: restarter
    spec:
      containers:
      - image: ghcr.io/jithinkv20/kuberest:master
        imagePullPolicy: Always
        name: restarter
        env:
        - name: KUBECONFIG
          value: ""
        volumeMounts:
        - mountPath: /data/k3s.yaml
          name: kubeconfig
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kubeconfig
        hostPath:
          # directory location on host
          path: /data
          # this field is optional
          type: /etc/rancher/k3s
status: {}
